# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('eng_title', models.CharField(max_length=50, unique=True, verbose_name='Título en inglés')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('eng_description', models.TextField(verbose_name='Descripción en inglés')),
                ('image_1', stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name'), validators=[stdimage.validators.MinSizeValidator(400, 250), stdimage.validators.MaxSizeValidator(1000, 1000)], verbose_name='Imagen Principal')),
                ('image_2', stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name'), validators=[stdimage.validators.MinSizeValidator(400, 250), stdimage.validators.MaxSizeValidator(1000, 1000)], verbose_name='Imagen 2 (opcional)')),
                ('image_3', stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name'), validators=[stdimage.validators.MinSizeValidator(400, 250), stdimage.validators.MaxSizeValidator(1000, 1000)], verbose_name='Imagen 3 (opcional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('eng_name', models.CharField(max_length=50, verbose_name='Nombre en inglés')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('eng_title', models.CharField(max_length=50, unique=True, verbose_name='Título en inglés')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.Category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.SubCategory', verbose_name='Subcategoría'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set([('title', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name', 'subcategory')]),
        ),
    ]
