# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, unique=True, verbose_name='Área')),
                ('area_eng', models.CharField(max_length=50, unique=True, verbose_name='Área en inglés')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('description_eng', models.TextField(verbose_name='Descripción en inglés')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('name_eng', models.CharField(max_length=50, unique=True, verbose_name='Nombre en inglés')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('eng_title', models.CharField(max_length=50, unique=True, verbose_name='Título en inglés')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('eng_content', models.TextField(verbose_name='Contenido en inglés')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Texto',
                'verbose_name_plural': 'Textos',
            },
        ),
    ]
