# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models
import stdimage.utils
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('eng_description', models.TextField(verbose_name='Descripción en inglés')),
                ('image_1', stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name'), validators=[stdimage.validators.MinSizeValidator(400, 250), stdimage.validators.MaxSizeValidator(1000, 1000)], verbose_name='Imagen Principal')),
                ('image_2', stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name'), validators=[stdimage.validators.MinSizeValidator(400, 250), stdimage.validators.MaxSizeValidator(1000, 1000)], verbose_name='Imagen 2 (opcional)')),
                ('image_3', stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name'), validators=[stdimage.validators.MinSizeValidator(400, 250), stdimage.validators.MaxSizeValidator(1000, 1000)], verbose_name='Imagen 3 (opcional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('eng_name', models.CharField(max_length=50, unique=True, verbose_name='Nombre en inglés')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
